version: '3.6'

services:

  webserver:
    build:
      context: .docker/nginx
    restart: always
    volumes:
      - .:/var/www
    ports:
      - 8000:80
    networks:
      - projeto_db
    depends_on:
      - app

  app:
    image: peuamorim/simple_laravel_image
    #build:
     # context: .
    restart: always
    #volumes:
    #- .:/var/www
    networks:
      - projeto_db
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - db_data:/var/lib/mysql
    networks:
      - projeto_db

  redis:
    image: redis
    restart: always
    networks:
      - projeto_db


networks:
  projeto_db:
    driver: bridge

volumes:
  db_data:
    driver: local
